name: Build ZMK firmware

on: [push, pull_request, workflow_dispatch]

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      config-path: echo "config"
      build-matrix-path: echo "build.yaml"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Move files to root
        run: |
          mv zmk-config/build.yaml build.yaml
          mv zmk-config/config config

  build:
    needs: prepare
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
