name: Build ZMK firmware

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    with:
      build_matrix_path: zmk-config/build.yaml
      config_path: zmk-config/config
      fallback_binary: bin # Optional: use default if needed
      archive_name: firmware # Optional: use default if needed
